/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat May 27 10:58:45 2023. */

#include "stm32msg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const EnumCmd reqMsg_cmd_default = EnumCmd_CMD_SYS_INFO;
const uint32_t aiTensorDescMsg_format_default = 0u;
const uint32_t aiTensorDescMsg_size_default = 0u;
const uint32_t aiTensorDescMsg_n_dims_default = 1u;
const float aiTensorDescMsg_scale_default = 0;
const int32_t aiTensorDescMsg_zeropoint_default = 0;
const uint32_t aiTensorDescMsg_addr_default = 0u;
const uint32_t aiTensorDescMsg_flags_default = 0u;
const uint32_t aiDataMsg_type_default = 0u;
const uint32_t aiDataMsg_addr_default = 0u;


const pb_field_t reqMsg_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, reqMsg, reqid, reqid, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, reqMsg, cmd, reqid, &reqMsg_cmd_default),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, reqMsg, param, cmd, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, reqMsg, name, param, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, reqMsg, opt, name, 0),
    PB_LAST_FIELD
};

const pb_field_t aiTensorDescMsg_fields[10] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, aiTensorDescMsg, name, name, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, aiTensorDescMsg, format, name, &aiTensorDescMsg_format_default),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, aiTensorDescMsg, size, format, &aiTensorDescMsg_size_default),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, aiTensorDescMsg, n_dims, size, &aiTensorDescMsg_n_dims_default),
    PB_FIELD(  5, UINT32  , REPEATED, CALLBACK, OTHER, aiTensorDescMsg, dims, n_dims, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, aiTensorDescMsg, scale, dims, &aiTensorDescMsg_scale_default),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, aiTensorDescMsg, zeropoint, scale, &aiTensorDescMsg_zeropoint_default),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, aiTensorDescMsg, addr, zeropoint, &aiTensorDescMsg_addr_default),
    PB_FIELD(  9, UINT32  , REQUIRED, STATIC  , OTHER, aiTensorDescMsg, flags, addr, &aiTensorDescMsg_flags_default),
    PB_LAST_FIELD
};

const pb_field_t aiDataMsg_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, aiDataMsg, type, type, &aiDataMsg_type_default),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, aiDataMsg, size, type, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, aiDataMsg, addr, size, &aiDataMsg_addr_default),
    PB_FIELD(  4, BYTES   , REQUIRED, CALLBACK, OTHER, aiDataMsg, datas, addr, 0),
    PB_LAST_FIELD
};

const pb_field_t aiOperatorMsg_fields[7] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, aiOperatorMsg, name, name, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, aiOperatorMsg, type, name, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, aiOperatorMsg, id, type, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, aiOperatorMsg, duration, id, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, aiOperatorMsg, counter_type, duration, 0),
    PB_FIELD(  6, UINT32  , REPEATED, CALLBACK, OTHER, aiOperatorMsg, counters, counter_type, 0),
    PB_LAST_FIELD
};

const pb_field_t aiTensorMsg_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, aiTensorMsg, desc, desc, &aiTensorDescMsg_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, aiTensorMsg, data, desc, &aiDataMsg_fields),
    PB_LAST_FIELD
};

const pb_field_t aiModelInfoMsg_fields[17] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, aiModelInfoMsg, name, name, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, rtid, name, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, signature, rtid, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, compile_datetime, signature, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, runtime_version, compile_datetime, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, tool_version, runtime_version, 0),
    PB_FIELD(  7, UINT64  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, n_macc, tool_version, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, n_nodes, n_macc, 0),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, n_inputs, n_nodes, 0),
    PB_FIELD( 11, MESSAGE , REPEATED, CALLBACK, OTHER, aiModelInfoMsg, inputs, n_inputs, &aiTensorDescMsg_fields),
    PB_FIELD( 12, UINT32  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, n_outputs, inputs, 0),
    PB_FIELD( 13, MESSAGE , REPEATED, CALLBACK, OTHER, aiModelInfoMsg, outputs, n_outputs, &aiTensorDescMsg_fields),
    PB_FIELD( 14, UINT32  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, n_activations, outputs, 0),
    PB_FIELD( 15, MESSAGE , REPEATED, CALLBACK, OTHER, aiModelInfoMsg, activations, n_activations, &aiTensorDescMsg_fields),
    PB_FIELD( 16, UINT32  , REQUIRED, STATIC  , OTHER, aiModelInfoMsg, n_params, activations, 0),
    PB_FIELD( 17, MESSAGE , REPEATED, CALLBACK, OTHER, aiModelInfoMsg, params, n_params, &aiTensorDescMsg_fields),
    PB_LAST_FIELD
};

const pb_field_t syncMsg_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, syncMsg, version, version, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, syncMsg, capability, version, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, syncMsg, rtid, capability, 0),
    PB_LAST_FIELD
};

const pb_field_t sysinfoMsg_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, sysinfoMsg, devid, devid, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, sysinfoMsg, sclock, devid, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, sysinfoMsg, hclock, sclock, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, sysinfoMsg, cache, hclock, 0),
    PB_LAST_FIELD
};

const pb_field_t ackMsg_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, ackMsg, param, param, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, ackMsg, error, param, 0),
    PB_LAST_FIELD
};

const pb_field_t logMsg_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, logMsg, level, level, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, logMsg, str, level, 0),
    PB_LAST_FIELD
};

const pb_field_t respMsg_fields[11] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, respMsg, reqid, reqid, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, respMsg, state, reqid, 0),
    PB_ONEOF_FIELD(payload,  10, MESSAGE , ONEOF, STATIC  , OTHER, respMsg, sync, state, &syncMsg_fields),
    PB_ONEOF_FIELD(payload,  11, MESSAGE , ONEOF, STATIC  , UNION, respMsg, sinfo, state, &sysinfoMsg_fields),
    PB_ONEOF_FIELD(payload,  12, MESSAGE , ONEOF, STATIC  , UNION, respMsg, ack, state, &ackMsg_fields),
    PB_ONEOF_FIELD(payload,  13, MESSAGE , ONEOF, STATIC  , UNION, respMsg, log, state, &logMsg_fields),
    PB_ONEOF_FIELD(payload,  15, MESSAGE , ONEOF, STATIC  , UNION, respMsg, data, state, &aiDataMsg_fields),
    PB_ONEOF_FIELD(payload,  16, MESSAGE , ONEOF, STATIC  , UNION, respMsg, op, state, &aiOperatorMsg_fields),
    PB_ONEOF_FIELD(payload,  17, MESSAGE , ONEOF, STATIC  , UNION, respMsg, tensor, state, &aiTensorMsg_fields),
    PB_ONEOF_FIELD(payload,  22, MESSAGE , ONEOF, STATIC  , UNION, respMsg, minfo, state, &aiModelInfoMsg_fields),
    PB_LAST_FIELD
};
















/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(aiTensorMsg, desc) < 65536 && pb_membersize(aiTensorMsg, data) < 65536 && pb_membersize(respMsg, payload.sync) < 65536 && pb_membersize(respMsg, payload.sinfo) < 65536 && pb_membersize(respMsg, payload.ack) < 65536 && pb_membersize(respMsg, payload.log) < 65536 && pb_membersize(respMsg, payload.data) < 65536 && pb_membersize(respMsg, payload.op) < 65536 && pb_membersize(respMsg, payload.tensor) < 65536 && pb_membersize(respMsg, payload.minfo) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_reqMsg_aiTensorDescMsg_aiDataMsg_aiOperatorMsg_aiTensorMsg_aiModelInfoMsg_syncMsg_sysinfoMsg_ackMsg_logMsg_respMsg)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(aiTensorMsg, desc) < 256 && pb_membersize(aiTensorMsg, data) < 256 && pb_membersize(respMsg, payload.sync) < 256 && pb_membersize(respMsg, payload.sinfo) < 256 && pb_membersize(respMsg, payload.ack) < 256 && pb_membersize(respMsg, payload.log) < 256 && pb_membersize(respMsg, payload.data) < 256 && pb_membersize(respMsg, payload.op) < 256 && pb_membersize(respMsg, payload.tensor) < 256 && pb_membersize(respMsg, payload.minfo) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_reqMsg_aiTensorDescMsg_aiDataMsg_aiOperatorMsg_aiTensorMsg_aiModelInfoMsg_syncMsg_sysinfoMsg_ackMsg_logMsg_respMsg)
#endif


/* @@protoc_insertion_point(eof) */
